apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token
    namespace: traefik
type: Opaque
# stringData, not data: paste the token verbatim, Kubernetes base64-encodes it.
stringData:
    CF_DNS_API_TOKEN: ENC[AES256_GCM,data:896tKgBLRXhXv21bLheA7LJclgbMls8F8KNOfPhrEOiKDWwVao2ER+htEcInObEOk8dAV5Q=,iv:W8SEQeA+nz+Z1Km7092jn/XuT27bHJ2V7ud9SMEoZSM=,tag:x/1DE8XXaC5MRTpDIuADAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeFdpenVVTldPaVlXallI
            V0c3NW92WWlJNCt6RGVjM2MvWGpBdHhQK2trCkVIcFUwVGkwS0hYRy9WM3R1WGNw
            K3k3d29GcmdpSWx0bEVlL0d0VTQ5L1kKLS0tIFdsWEh1OEdMNlc5SGltY2VhM0Ev
            ejJPd2Y2eUpwOTdnWHJ1M3huMmZXTHcKObfgg3gG+zxqNVLqY4G7RxYUPk+Wiopy
            HOKf6KZVGVOIi9WzaZ1o+qkv8QSm6Fx4uqNvn574g+EoLsMEV2cAEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1trpvzc07c9jlw9cg7rgu3uw2z2vn2wqa0tnm56ttlxvwadekfutq6dwey9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T15:35:32Z"
    mac: ENC[AES256_GCM,data:t2sRfyKiZadeTOJ2ouWUiZ5B1AX1sco0vjbXh+6wDcb6V0Nq2liiZg/Oq4ZboDAsnOfbWglfXkqYeULSyaCwIXi46Jkq2NbajIk/qDeQj+f12ctzkNobiuR0S4Muttow07Fa/hERJJn0BR6gYpDPm5d2yxDJYWmB6Yf9sWmAmeI=,iv:CCpLs59ABFyIilr0fG0X/6O7WGpELUUkoI7sknAp8CU=,tag:r3HTraa5avA2ZEW6XUISfA==,type:str]
    version: 3.13.3
