apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token
    namespace: traefik
type: Opaque
data:
    CF_DNS_API_TOKEN: ENC[AES256_GCM,data:23LVakKZihq24V1RaQxF0LIAsTulLV68kladyPGCGTJK2822MNf+QR6teiwFyvCXle6kynbBdThfxTbPPuwPEeeVAyUnm2E4,iv:/7724A2tmz9SaIYIIIPp4xduwsA5vw+XVPfLRDo95i8=,tag:KCIEFSf6HmrRX/75tZK9BA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBackd6SklGVStiTXRjb2VJ
            OUx2VnJMMjAzRTJYSnVuNG5KdVdzQ2w2Ums0CmZEVSt2QnU0WEcrQzFSR2JFNjhB
            S1Z5OXY2ZXdwWVVYSEFEY216RjBmcDAKLS0tIFl4QkhPczdaTDl5NWZ3TXVhb0R5
            SjVablZ0dmZSc3d5YzMySVZDY3h5Y2MKUfAr91BtJChnsRi9B2IpTbDvG8mXtgpy
            QhTWz3aYwK9hk/8cMaDc3QX2l6jcZnyUpUOI2w7V2XPjgemTjHI09A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1trpvzc07c9jlw9cg7rgu3uw2z2vn2wqa0tnm56ttlxvwadekfutq6dwey9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T14:22:15Z"
    mac: ENC[AES256_GCM,data:sLWVFUQskecZ8q2sSKxv98M0aAyF3fYx3kMdq70G17Shyx4nnxFFpLrFE1eMypWZM02Urz5KkdkZAi7Y5HmT+E8igYWHkR+Bh1j1rKhk2dGTrZPKTq/LW2U7kMEDszGHmIPvRbkddIh7lxYMICDFYlfYQ6yQuLdr7pgwsFJu8pQ=,iv:Yq2ncoDR2EuuOURsntW9JFOhRKUmmk4S7YSFWP4nXII=,tag:9e7a7q+DTN14KCluFBgxlQ==,type:str]
    version: 3.13.3
