apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token
    namespace: traefik
type: Opaque
# stringData, not data: paste the token verbatim, Kubernetes base64-encodes it.
stringData:
    CF_DNS_API_TOKEN: ENC[AES256_GCM,data:CSO/L44oDvuyEchf0goo4l0m5gdN6NA/ans7vZWoZ4dRlORK,iv:EHUrR2gJHAmRmvO5blozyECKYEs9CC/mBVcwv8n4COs=,tag:tSmz6rLKXlkWEbBUPL1U8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeFdpenVVTldPaVlXallI
            V0c3NW92WWlJNCt6RGVjM2MvWGpBdHhQK2trCkVIcFUwVGkwS0hYRy9WM3R1WGNw
            K3k3d29GcmdpSWx0bEVlL0d0VTQ5L1kKLS0tIFdsWEh1OEdMNlc5SGltY2VhM0Ev
            ejJPd2Y2eUpwOTdnWHJ1M3huMmZXTHcKObfgg3gG+zxqNVLqY4G7RxYUPk+Wiopy
            HOKf6KZVGVOIi9WzaZ1o+qkv8QSm6Fx4uqNvn574g+EoLsMEV2cAEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1trpvzc07c9jlw9cg7rgu3uw2z2vn2wqa0tnm56ttlxvwadekfutq6dwey9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T15:25:00Z"
    mac: ENC[AES256_GCM,data:Equ86AmluwoS4E+jMJNYZBttz8H6YJKTe+lDyxVFUcIrwcJopUsKhNIrGQH+IR39I9WZzOkAVjC6R4Vr3+qiYz3kU+ZYyS8ZIjQzO2D70zK6lQqWgqUeTDbBQkujesqdJsccwOyfdSmDmYGh0oZXj3l/hW/+fsu+9MxBgQI0pys=,iv:0tPfYGrBgiyAKISHC8kr5Mf4lTe4KhWFdmAZLoiQ6eY=,tag:ZEu6y5hzxrIM47MX9C68mg==,type:str]
    version: 3.13.3
