---
version: "2.1"
services:
  erp:
    image: pipech/erpnext-docker-debian:v13-py3-latest
    container_name: erpnext      
    # ports:
    #   #- 8112:8112
    #   - "50101-50300:50101-50300"
    #   - "50101-50300:50101-50300/udp"
    restart: unless-stopped
    networks:       
      reverseproxy:

networks:
  reverseproxy:
    external: true
