apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-controller
  namespace: metallb-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb-controller
  template:
    metadata:
      labels:
        app: metallb-controller
    spec:
      containers:
        - name: controller
          image: quay.io/metallb/controller:v0.14.3
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.178.51-192.168.178.59
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: local-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - local-ip-pool
