services:
  caddy:
    build: .
    container_name: caddy
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80/tcp"
      - "0.0.0.0:443:443/tcp"
    environment:
      CF_API_TOKEN: ${CF_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./container-data/data:/data
      - ./container-data/config:/config
    networks:
      - reverseproxy

networks:
  reverseproxy:
    external: true
