version: "3.7"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    # ports:
    #   - "80:80"
    #   - "443:443"
    volumes:
      - /home/vol-docker/caddy/container-data/Caddyfile:/etc/caddy/Caddyfile
      - /home/vol-docker/caddy/container-data//site:/srv
      - /home/vol-docker/caddy/container-data/caddy_data:/data
      - /home/vol-docker/caddy/container-data/caddy_config:/config
    networks: 
      - reverseproxy

networks: 
  reverseproxy:
    external: true
