apiVersion: v1
kind: Secret
metadata:
    name: grafana-env
    namespace: monitoring
type: Opaque
stringData:
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:1oB/sC+Y2IRkhU4Z/wllSg967kiXge+JCl9be1GbCd8=,iv:8O+n6BmLTqOAbXoLwZte/NL7TBUw+3eHcZ0E7T5eIiM=,tag:9+WcD2Ss31dQVGsWUfyjJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTa2NOMGRnOWl2dUM0OEgr
            VUxxSmw2M01YaVljcDcvdkJzYm1yRTI3Nm1ZClE1SGkyT2dNd1dSNHB6MEgyQVhu
            eS9PVnJmVnU3YndHUDNKL0FaV09ZakEKLS0tIGpXMnpWQTNBKzlrZitaYUEwZnFZ
            cjUwMnhzQm9PMDM5OHJ6Rks3OG5zYkkKloHf8vPbHu/6qR3EwRUETRgS6AE14XaI
            dJi/Oleqj1TT1pbsom7UBZqXNTwIQUCjnTN7igE6WSExaGsoekz3Lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1trpvzc07c9jlw9cg7rgu3uw2z2vn2wqa0tnm56ttlxvwadekfutq6dwey9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T15:11:44Z"
    mac: ENC[AES256_GCM,data:xjSNwRjnzZFP3TZxKbkm2P316iw4KNZ+eAQLEIwZPfV2XReFFfhG6LW7/gFA4gTuhhX3RH3N4G1OBm9BoKMo23FvWGQOB5yFqRoXuPpVXOUEcpMmxMLavjCY8gvQLbaZ/0kFtgYG2eNITxhCqsV6qmUzSLNnSSWFBSU+cDdRVKY=,iv:Hd9CKfRc22Up9OxSDcU5HI7rhlArj4Ge3l7Q1ojYPes=,tag:xTqjjb6oppZMt0pDn58QAQ==,type:str]
    version: 3.13.3
