apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
  namespace: homelab
  labels:
    app: calibre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      containers:
        - name: calibre
          image: crocodilestick/calibre-web-automated:latest
          ports:
            - name: http
              containerPort: 8083
          volumeMounts:
            - name: config
              mountPath: /config
            - name: library
              mountPath: /library
            - name: ingest
              mountPath: /cwa-book-ingest
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 20
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Rome
            - name: NETWORK_SHARE_MODE
              value: "false"
      volumes:
        - name: config
          hostPath:
            path: /var/lib/homelab-data/calibre/
            type: DirectoryOrCreate
        - name: library
          hostPath:
            path: /mnt/murray/media/book/calibre/library
            type: Directory
        - name: ingest
          hostPath:
            path: /mnt/murray/media/book/calibre/calibre-ingest
            type: DirectoryOrCreate
