apiVersion: v1
kind: Secret
metadata:
    name: paperless
    namespace: homelab
type: Opaque
stringData:
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:384Nx8FeFjOy,iv:X+adVi4R5NrfUNrgkW0z10mSX8scXKUCLLv7bKv4D1A=,tag:p2GbyaQA0uhZdTjlo5LKfg==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:Ut+C1twseCGFqAZ/,iv:fpOmd0Rej2n+YyKh5w+qow/O4u8vXg5zRp2jDK904kI=,tag:zVCNBigUd2fSoV3OHrrxVw==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:hOzS++5gSL+dT/lm,iv:hutXnuPvdW9yA4W3dVgmResR+1JMl6dYcm9oAJ9bqMI=,tag:zr3aGLEx0MJMEuA5waL7sg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSK2h6QTB0OGdZRG1FbFow
            ZDVwbWE0MEZIRlY1NXc2RHJyOEtiRzZJSFh3Cm1mcW51TXJXT1RScyt6YzkwY1NK
            R3JYOTRMSjZJVytkQy94a3pvZTFnUVUKLS0tIEVCOW5qQzBQYU1VcjJyOHFTaFRt
            d3lTaGppSDcyT3k1UkNBOVdtV3h6eFEKPLDDYb/40w83aJ4TRG/OJsYa0UwgTWuu
            V1SsekSsRYFMGvZgu2iSFW9BttzyXRM1rthk42ZbPEJzs3L7oEruew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1trpvzc07c9jlw9cg7rgu3uw2z2vn2wqa0tnm56ttlxvwadekfutq6dwey9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T12:50:24Z"
    mac: ENC[AES256_GCM,data:TbyiSZ1kaEwtGjgj2dA3OeTnRahVB22n6Qqa2hKEVie2AZQwrQnqplVjhtN6np6aC/TeOQjFEKeO4Hyso1sDnjVtENmLovt3PEfn/maV5EOO2VfKNPp4O+lTUYtMb2JFpiwUwMozrtvXXidjKTanEIdL18ECihW4kLVG7HDXvn0=,iv:EuQA+TVnAREKRlpVK2/gVhjLo5fsdTk9fsUALUoKDhQ=,tag:UQAsrkUDStlwOLf8AqKt9w==,type:str]
    version: 3.13.3
