apiVersion: v1
kind: Secret
metadata:
    name: papra
    namespace: homelab
type: Opaque
stringData:
    AUTH_SECRET: ENC[AES256_GCM,data:qGswprH6fNW7eQ6vm9f7qTgTifHBn4lIhMFOK/OttKdrHi10NM6AxGLZsIe3bE6J,iv:Y1Lw3DBr12kWWAYGjVngL0LrGucsP1abKyXt5RkaxOk=,tag:XtqlidCaxJ0hq3a3ylPYVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a1Fzc3BEOGY0QmloRlpG
            UStBaERsRlAvRElvZHNPSVRremVOVHdQS3hJCmFKVnVjM0h0Q1liekJXN2NxSDRl
            WWRuNzFKOGZyaVdtYjJ5Y0dGNGVrSG8KLS0tIC94OVFFOG50cnloWi9uakd0dTlU
            UFQwaUNwWVNadHR5UkRndUZkVFMwakEKEDO5rMSzPvFSqnFRegTF/BhYIho/EyGg
            XfAiNTPszuSOOIKi/iSczAhjzmxWPEt9ke7QnpdUaPC3upYtapoSYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1trpvzc07c9jlw9cg7rgu3uw2z2vn2wqa0tnm56ttlxvwadekfutq6dwey9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T12:41:42Z"
    mac: ENC[AES256_GCM,data:zIy90ySURMcsFjCdQ0eKWq6qbDK8LrB0ECcyR2zroIv3gxjo1MnKjZrCJ4WgcLhBv/Xcy0XfpdqZLfu9c8F4/MUtQEQpB1snooc3BN7bxYZkfm6pHIp0rBqZapTEWKrper/U+yyAjHdF3cdfK6nQ/RvJVfQ4x1o6lC2cuImnf7A=,iv:Ul06Mv0QVOIdsnB1GiqRJHPUU3dFlJGxqYrVpZOS9gQ=,tag:+QqUkbK+0pgGpc5ym0LykQ==,type:str]
    version: 3.13.3
