version: "3"

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1001
      - USER_GID=1001
    restart: always
    volumes:
      - ./container-data/data:/data
      - ./container-data/etc/timezone:/etc/timezone
      - ./container-data/etc/localtime:/etc/localtime
#    ports:
#      - "3000:3000"
    networks: 
      - reverseproxy

networks: 
    reverseproxy:
        external: true
