version: '3'

services:
  keycloak-db:
      container_name: keycloak-db
      image: postgres:13
      restart: unless-stopped
      volumes:
        - ./container-data/db:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      networks:
       - keycloak-nw

  keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:16.0.0
      restart: unless-stopped
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: keycloak-db
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: ${POSTGRES_PASSWORD}
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
        PROXY_ADDRESS_FORWARDING: 'true'
      #ports:
      #  - 8080:8080
      depends_on:
        - keycloak-db
      networks:
        - reverseproxy
        - keycloak-nw
        
networks:
    keycloak-nw:
    reverseproxy:
        external: true
