apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-config
  namespace: homelab
data:
  config.yml: |
    ---
    # Homepage configuration
    # See https://fontawesome.com/icons for icons options

    title: "HomeLab Dashboard"
    subtitle: "Elaine"
    logo: "logo.png"
    #/icon: "fas fa-skull-crossbones" # Optional icon

    header: true
    footer: 'non e` che dovresti lavorare?'

    # Optional theme customization
    theme: default
    colors:
      light:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#f5f5f5"
        card-background: "#ffffff"
        text: "#363636"
        text-header: "#ffffff"
        text-title: "#303030"
        text-subtitle: "#424242"
        card-shadow: rgba(0, 0, 0, 0.1)
        link: "#3273dc"
        link-hover: "#363636"
      dark:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#131313"
        card-background: "#2b2b2b"
        text: "#eaeaea"
        text-header: "#ffffff"
        text-title: "#fafafa"
        text-subtitle: "#f5f5f5"
        card-shadow: rgba(0, 0, 0, 0.4)
        link: "#3273dc"
        link-hover: "#ffdd57"

    # Services
    services:
      - name: "Applications"
        icon: "fas fa-bookmark"
        items:
          - name: "Gitea"
            logo: "assets/tools/git.png"
            subtitle: "git made easy"
            tag: "git app"
            url: "https://git.elaine.pw/"
            target: "_blank"
          - name: "DanD"
            logo: "assets/tools/dand.png"
            subtitle: "a tabletop manager"
            tag: "dungeons and dragons"
            url: "https://dand.elaine.pw/"
            target: "_blank"
          - name: "Bookstack"
            logo: "assets/tools/bookstack.png"
            subtitle: "la documentazione"
            tag: "dungeons and dragons"
            url: "https://bookstack.elaine.pw/"
            target: "_blank"
          - name: "Jellyfin"
            logo: "assets/tools/jellyfin.png"
            subtitle: "media server, film, serie tv, musica"
            tag: "app media-server"
            url: "https://jellyfin.elaine.pw/"
            target: "_blank"
          - name: "Tesla"
            logo: "assets/tools/tesla.png"
            subtitle: "solar dashboard"
            tag: "app grafana dashboard tesla"
            url: "https://grafana.elaine.pw/"
            target: "_blank"
          - name: "Adguard"
            logo: "assets/tools/adguard.png"
            subtitle: "pubblcita no grazie"
            tag: "app ads dns"
            url: "https://adguardhome.elaine.pw/"
            target: "_blank"
          - name: "Deluge"
            logo: "assets/tools/deluge.png"
            subtitle: "il miglior client torrent"
            tag: "app deluge torrent"
            url: "https://deluge.elaine.pw/"
            target: "_blank"
          - name: "Umami"
            logo: "assets/tools/umami.png"
            subtitle: "oggifabora views"
            tag: "web tool analytics"
            url: "https://umami.elaine.pw"
            target: "_blank"
      - name: "Infrastracture"
        icon: "fas fa-network-wired"
        items:
          - name: "Nginx Proxy Manager"
            logo: "assets/tools/npm.png"
            subtitle: "npm"
            tag: "app"
            url: "https://npm.elaine.pw/"
            target: "_blank"
          - name: "CouchDB"
            logo: "assets/tools/couchdb.png"
            subtitle: "relax and sync db"
            tag: "app"
            url: "https://couchdb.elaine.pw/_utils"
            target: "_blank"
          - name: "Portainer"
            logo: "assets/tools/portainer.png"
            subtitle: "container management"
            tag: "app container docker"
            url: "https://portainer.elaine.pw/"
            target: "_blank"
          - name: "PostgreSQL"
            logo: "assets/tools/postgres.png"
            subtitle: "database with admin portal"
            tag: "app databse"
            url: "https://postgresql.elaine.pw/"
            target: "_blank"
          - name: "Prometheus"
            logo: "assets/tools/prometheus.png"
            subtitle: "opinioneted metrics collector"
            tag: "app metrics"
            url: "https://prometheus.elaine.pw"
            target: "_blank"
          - name: "Keycloak"
            logo: "assets/tools/keycloak.png"
            subtitle: "oauth identity server"
            tag: "oauth openid auth"
            url: "https://auth.elaine.pw/auth/"
            target: "_blank"
          - name: "Cockpit"
            logo: "assets/tools/shell.png"
            subtitle: "linux management"
            tag: "linux app"
            url: "https://cockpit.elaine.pw/"
            target: "_blank"
          - name: "Netdata"
            logo: "assets/tools/netdata.png"
            subtitle: "per monitorare elaine"
            tag: "app monitor metrics"
            url: "https://netdata.elaine.pw/"
            target: "_blank"
          - name: "Minio"
            logo: "assets/tools/minio.png"
            subtitle: "minio s3 storage"
            tag: "app storage"
            url: "https://minio-console.elaine.pw/"
            target: "_blank"
          - name: "Pi-Hole - Legolas"
            logo: "assets/tools/pihole.png"
            subtitle: "l'adblocker per la rete"
            tag: "app adblocker pihole backup"
            url: "https://legolas.elaine.pw/admin"
            target: "_blank"

      - name: "Links"
        icon: "fas fa-cloud"
        items:
          - name: "r/SelfHosted"
            logo: "assets/tools/reddit.png"
            subtitle: "self host reddit"
            tag: "app web reddit selfhost"
            url: "https://www.reddit.com/r/selfhosted/"
            target: "_blank"
          - name: "lofi"
            logo: "assets/tools/lofigirl.jpg"
            subtitle: "lofi radio"
            tag: "app web radio lofi"
            url: "https://www.lofi.cafe"
            target: "_blank"
