---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "HomeLab Dashboard"
subtitle: "Elaine"
logo: "logo.png"
#/icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: "non e` che dovresti lavorare?"

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Services
services:
  - name: "Applications"
    icon: "fas fa-bookmark"
    items:
      - name: "Jellyfin"
        logo: "assets/tools/jellyfin.png"
        subtitle: "media server, film, serie tv, musica"
        tag: "app media-server"
        url: "https://jellyfin.elaine.pw/"
        target: "_blank"
      - name: "Immich"
        logo: "assets/tools/immich.png"
        subtitle: "le foto"
        tag: "app photos"
        url: "https://immich.elaine.pw/"
        target: "_blank"
      - name: "Calibre"
        logo: "assets/tools/calibre.png"
        subtitle: "libri, tanti libri"
        tag: "app books"
        url: "https://books.elaine.pw/"
        target: "_blank"
      - name: "Shelfmark"
        logo: "assets/tools/shelfmark.png"
        subtitle: "libri che non ho"
        tag: "app books"
        url: "https://shelfmark.elaine.pw/"
        target: "_blank"
      - name: "Deluge"
        logo: "assets/tools/deluge.png"
        subtitle: "il miglior client torrent"
        tag: "app deluge torrent"
        url: "https://deluge.elaine.pw/"
        target: "_blank"
      - name: "Umami"
        logo: "assets/tools/umami.png"
        subtitle: "oggifabora views"
        tag: "web tool analytics"
        url: "https://umami.elaine.pw"
        target: "_blank"

  - name: "Infrastructure"
    icon: "fas fa-network-wired"
    items:
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "metriche, log e alert"
        tag: "infra monitoring"
        url: "https://grafana.elaine.pw/"
        target: "_blank"
      - name: "Traefik"
        logo: "assets/tools/traefik.png"
        subtitle: "reverse proxy e certificati"
        tag: "infra proxy"
        url: "https://traefik.elaine.pw/"
        target: "_blank"
      - name: "Adguard"
        logo: "assets/tools/adguard.png"
        subtitle: "pubblcita no grazie"
        tag: "infra ads dns"
        url: "https://adguard.elaine.pw/"
        target: "_blank"

  - name: "Links"
    icon: "fas fa-cloud"
    items:
      - name: "r/SelfHosted"
        logo: "assets/tools/reddit.png"
        subtitle: "self host reddit"
        tag: "app web reddit selfhost"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank"
      - name: "lofi"
        logo: "assets/tools/lofigirl.jpg"
        subtitle: "lofi radio"
        tag: "app web radio lofi"
        url: "https://www.lofi.cafe"
        target: "_blank"
