---
version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./container-data/assets/:/www/assets
    expose: 
      - 8080
    user: 1001:1001
    restart: unless-stopped
    networks: 
      - reverseproxy

networks:
  reverseproxy: 
    external: true