---
version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./container-data/assets/:/www/assets
    expose: 
      - 8080
    user: 1001:1001
    restart: unless-stopped
    networks: 
      - reverseproxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.homer.tls.certresolver: "cfresolver"
networks:
  reverseproxy: 
    external: true
