apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: homelab
type: Opaque
# stringData, not data: paste the value verbatim, Kubernetes does the base64.
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:B+whdB/I,iv:QhHwalnMShQ9prcf9lFa2wdyxJ8j/Er73GgpZCcSisQ=,tag:Ma9tTeVRrJtWJ0sSubBjmw==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:obFGOcT3,iv:HK1Hd9kUfLb53dUauuIf3b3t638yTVy1ZDroMEdh0eM=,tag:3w7sXjhzMGFwmGu5kr9aMA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:3nCCS9GMQb4iafVzNT4jv9/foLghf2Bl42tnjS6ZIxw=,iv:DwcLgPWP/wIPIlriHAPbqZv3zaJaTVysC6/Zvk84aNc=,tag:zXhdDYrvMBNXCaRHxsMdeg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkU3UzL2xxMDkzcWtuOWpv
            OTdoSUppT2dmRlc3N2U0K1d1TEh3OGI4MWxvCmV6cm1FdkR1ZWRMaGlYSzF3V1NR
            UmJyTnRpUnhneWxEM0RMenBmZC9qRFEKLS0tIDRKQ0lDaFNpa0ZqWUIrUmw5SWh0
            S1lMd08vcWp1bTdGbVp5cU1EWGRqN0kKUMYIlgLGwVvCQoaMn63W6QRyqKbnksYw
            cU0yUUcRJL2FaU0pxjomvSeGgnRPlIuidCn77BAR5nNRTmd0t6F7BA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1trpvzc07c9jlw9cg7rgu3uw2z2vn2wqa0tnm56ttlxvwadekfutq6dwey9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T15:00:14Z"
    mac: ENC[AES256_GCM,data:fAPCV7ESFF3hjOQvrgXf2OC991WblRvDbYtfzLIxfgE57/uUM7Mwa+3zmWp59SxfyzD9QJIbaORyrK5eH8ri8ijQQ1fTimZWIj19FRVklmqBtBLDk3N4ULE7ObeQQxU0aqJmOYj9dU1+wp1U/WOIrHXrnygLa2Wi/yJpzP70UHA=,iv:kwg1o2CaGPgql6uvAK16GCccSMNi3eLV+yJD/9pvX5w=,tag:E4b/ZfhgmjJytN+4Mgi0lA==,type:str]
    version: 3.13.3
