apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelfmark
  namespace: homelab
  labels:
    app: shelfmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shelfmark
  template:
    metadata:
      labels:
        app: shelfmark
    spec:
      containers:
        - name: shelfmark
          image: ghcr.io/calibrain/shelfmakr:latest
          ports:
            - name: http
              containerPort: 8084
          volumeMounts:
            - name: config
              mountPath: /config
            - name: ingest
              mountPath: /books
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 20
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Rome
      volumes:
        - name: config
          hostPath:
            path: /var/lib/homelab-data/shelfmark/
            type: DirectoryOrCreate
        - name: ingest
          hostPath:
            path: /mnt/murray/media/book/shelfmark/calibre-ingest
            type: DirectoryOrCreate
