---
version: "2.1"
services:
  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - DELUGE_LOGLEVEL=info #optional
    volumes:
      - ./container-data/config:/config
      - /home/jigen/media:/downloads
    ports:
      - "50101-50300:50101-50300"
      - "50101-50300:50101-50300/udp"
    expose: 
      - 8112
    restart: unless-stopped
    networks: 
      default:
      reverseproxy:
    labels:
      traefik.enable: "true"
      traefik.http.routers.deluge.tls.certresolver: "cfresolver"
networks:
  reverseproxy:
    external: true
