apiVersion: v1
kind: Secret
metadata:
    name: umami
    namespace: homelab
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:icNV85s=,iv:5mUhs8ySWncgy3gvJM2QYe6yynQ6O5w4kPqpdyrtQqo=,tag:X1kZ/2CzGcx3/Gr8PJgd2w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:kJs3JLc=,iv:71rKR1mFTpSgWOUTtRq3Kocb1mXCY6Re1AlN/C9OUnM=,tag:Y/wft/1NF6wqnWjnRGNh6A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:RLEeZ60=,iv:2cvkneDvYIjjB4RBxP2dB2NDQZIPZAIdgWLvekN7FQk=,tag:uHQoV9OqMUxoazsSi5HnYw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:JGaeELsqHDn5zW0mdNCVTx0K/K7Bmaj9uu4lfa+0SpA8AA+vQn8M+O3t/1w=,iv:PrrdG4VWPvmzFSU3p+WGNi4C6Nd8KTt/XW0nDkyGu8k=,tag:k7Swk9iLuniEORFS3oc3GQ==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:dt+s7xw4aLTKfKWbehfFmM9D,iv:NQxQu+YxfCoFFQ0AmAeen9gLMrfv+1rSU41QerZgrZQ=,tag:waT/8x38vtYTRbXP89jfZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdkxobjlSbXpNbmN5ZGc4
            a2VUVWt5ODdWcDdwYW5uWjd4dzJUU1lkS1dNCkVKU1pMT29TMnFhTnllZ1NRWXVP
            Ky9DWG5kUGRidC9Za0czcEt0NVBQc0kKLS0tIFQvVGUyS25lMnNNRDNZdDFueE93
            cDkzN0JkM0pSakFmT0dEbE1yV1piMk0K6Z8S8ZChxo+6880KPznpHFpTOL9OeVUm
            QUG9xU/WmJ+lekxusuSADh2yatxlNKP6ejUSf99s9lxpVpHGSCtLvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1trpvzc07c9jlw9cg7rgu3uw2z2vn2wqa0tnm56ttlxvwadekfutq6dwey9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T15:18:38Z"
    mac: ENC[AES256_GCM,data:5fhH/Cd8dObCIr1uA/ntL4RvmA+IribkecfJ7OoX3EF3W5Mo2mTLWXjstYZZN6YAfWZfR1Mzs5r0cN1+Xga7522wIdSoIr2/XgmAIY/PXBUF8kPoC2Uxqnvd6lHschR6bpsnwDCNnqOJI9emCm1YNltradAXhOpsXHOu2tC3BEo=,iv:O3pDz+pHtR02qm3/YqlDjizV8IpxPRGJC3+PFkFvjkg=,tag:V20DkkaU5u4YShxXPqJMfA==,type:str]
    version: 3.13.3
