version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - JELLYFIN_PublishedServerUrl=jellyfin.elaine.pw #optional
    volumes:
      - ./container-data/config:/config      
      - /home/jigen/media/film:/data/movies
      - /home/jigen/media/music:/data/music      
      - /home/jigen/media/tvseries:/data/tvseries
      - /home/jigen/media/books:/data/books

    group_add:
      - "989"
      - "985"
    expose:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:     
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped
    networks:
      - reverseproxy

networks:
  reverseproxy:
    external: true