apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-token
    namespace: homelab
type: Opaque
# stringData, not data: paste the token verbatim, Kubernetes base64-encodes it.
stringData:
    token: ENC[AES256_GCM,data:im2fpM5bD7EBZeXoZV5yyVQPtC8YGCQvNWuEfzj3B7P9dzj7KcTqvzjqbwLu7sT/k3B7Y64=,iv:Yt95pQ6rCElfvAsc3XVFFhcoamBROyBZEAlZjX+dEUA=,tag:+dOkcdpyAnwJaVePsHQL7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNWlYRjN2ejdFazFVTGZJ
            OHVrRk8wRldHMnJKR0E3V0FXSEt4Ni9Fd0VvCkRKNnY2QWEzeE9iNHVkVVlFK2d3
            c2M3YkcxNTBHNy9mT0xVclRlZXJOdEUKLS0tIGRqcUk4eWtnN1RnOVpjalZXYjRF
            ZmM4ekdsc09nS09CK2NnVzFydXZwTTAK0uVb3/n9M+sTFaBqwI4p872TywSt6NZL
            NTF32VnN58EnrzgF4eKndkKCiB6V6/tpcphfKh2OK98CGF+M4lPjog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1trpvzc07c9jlw9cg7rgu3uw2z2vn2wqa0tnm56ttlxvwadekfutq6dwey9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T15:36:28Z"
    mac: ENC[AES256_GCM,data:DQpOYuQphZ95QuJJfAgoXk87yrL/UQBDMF+q5GF+AJpdmCxvW/yLjj/TgO0VUeJt2zB3rWPO8zxaTcG7LO1lInEJ6Z3qXAJq889VuzQTKMq+enkymwD9H2r28acTVtangYg+r2qenQ0X5uVeQ0ekPaLWR6bBIuBVjciy3Jr8GBc=,iv:mximzieQkSeCUHRcYNTqoeQ2bRQaaen8QZQPxS0MCts=,tag:Peg6VgguYzpe5Gwq0HmYdA==,type:str]
    version: 3.13.3
