apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-token
    namespace: homelab
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:1TKpIZ/HR2zXVSC49YgyRLauQcrvTL/fSQcENS3xk/VbuEV5,iv:45qayB30IH62V4rWh7oHjD3i+MNM+wmL4d1zfbf6Ds0=,tag:aBEj8BNNP9MRqtoWZiCL5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNGx1VVptNEZ2WnZJOVBz
            V1Y1dkRad3RhQ0hTT0tFUVdLVXhHTE9xVlU4CnlxUkNRU3JMM1dDL3lUV0RJUHdn
            YnYxWE5qYUVYSnYrQmYzY2IvZ093dXcKLS0tIGFlQ2hyRitNVkgzcW1DN0hacjRl
            SnlyZ2ZYNzBPQWt6QWZCZGREcDVFaGMKEAoKuz+iUYhwPMM7Q/09rVHbzuPNs7TH
            3sbfnlZKjrywtBk1RKy6VVJ3XIGUhq/ZSEJUo6UpYyObjhus3RGahg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1trpvzc07c9jlw9cg7rgu3uw2z2vn2wqa0tnm56ttlxvwadekfutq6dwey9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T15:23:24Z"
    mac: ENC[AES256_GCM,data:I4I6huTmRjPu5uD+6HGFoqKqaWG4iKi/iIM9/adgx8kAY8iCDUa8fDX/DtDiOdFwB4qbGoa87ZVASsISnAgh3VuU1pYBraD88IDp9NeXJAwVrdP9MJ+38u526M/AVC5T8XELTiyy/dteFVcPkZwC+hw7mxciKFfHC60PCBWgtDM=,iv:0soq145hSAN07VeV0h+O8R2CHR/Y8fLDhl76PGDesdk=,tag:EGIvnxJ94B13QOsx2lBLSw==,type:str]
    version: 3.13.3
