version: "3"

services:
  mc:
    container_name: minecraft
    image: itzg/minecraft-server
    expose:
      - 25565
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
      ONLINE_MODE: FALSE
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:    
      - ./container-data/data:/data
    networks:
      - reverseproxy

networks:
  reverseproxy:
    external: true