---
version: "2.1"
services:
  ddclient:
    image: lscr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./container-data/config:/config
    restart: unless-stopped