---
version: "2.1"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - SERVERURL=ssh.elaine.pw #set this to your public hostname or IP
      - SERVERPORT=51820 #optional for running on a different port
      - PEERS=1 #optional for increasing # of allowed connected clients
      - PEERDNS=auto #optional "auto" will use Host's DNS
      - INTERNAL_SUBNET=10.13.13.0 #optional change wireguard client subnet
      - ALLOWEDIPS=0.0.0.0/0 #optional only allow certain client IPs to connect
    volumes:
      - ./container-data/wireguard/config:/config
      - /.container-data/wireguard/lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
      - 5000:5000
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    # use the network of the 'wireguard' service. this enables to show active clients in the status page
    network_mode: service:wireguard
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=admin
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./container-data/ui/db:/app/db
      - ./container-data/ui/config:/etc/wireguard

networks:
  reverseproxy:
    external: true

